title: Kanav Gupta
name: Kanav
tagline: Aspiring Cryptology Researcher
username: kanav99
email: kanav0610@gmail.com
description: >-
  

baseurl: ""
url: "//kanavgupta.xyz"

markdown: kramdown
kramdown:
  highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false

collections:
  blog:
    output: true
    permalink: "/blog/:slug:output_ext"

defaults:
- scope:
    path: ""
    type: blog
  values:
    layout: blog

plugins:
- jekyll-feed
- jekyll-sitemap
- jekyll-seo-tag

exclude:
- Gemfile
- Gemfile.lock
- node_modules
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
- README.md
- .git/
- .gitignore
- .github/
